/*
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TessJsonApi) {
      root.TessJsonApi = {};
    }
    root.TessJsonApi.ContentProviderAttributes = factory(root.TessJsonApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ContentProviderAttributes model module.
   * @module model/ContentProviderAttributes
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>ContentProviderAttributes</code>.
   * @alias module:model/ContentProviderAttributes
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ContentProviderAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContentProviderAttributes} obj Optional instance to populate.
   * @return {module:model/ContentProviderAttributes} The populated <code>ContentProviderAttributes</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('image-url'))
        obj.imageUrl = ApiClient.convertToType(data['image-url'], 'String');
      if (data.hasOwnProperty('keywords'))
        obj.keywords = ApiClient.convertToType(data['keywords'], ['String']);
      if (data.hasOwnProperty('created-at'))
        obj.createdAt = ApiClient.convertToType(data['created-at'], 'Date');
      if (data.hasOwnProperty('updated-at'))
        obj.updatedAt = ApiClient.convertToType(data['updated-at'], 'Date');
    }
    return obj;
  }

  /**
   * The \"friendly\" identifier of the content provider.
   * @member {String} slug
   */
  exports.prototype.slug = undefined;

  /**
   * The title of the content provider.
   * @member {String} title
   */
  exports.prototype.title = undefined;

  /**
   * A description of the content provider.
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * The URL to the content provider's website.
   * @member {String} url
   */
  exports.prototype.url = undefined;

  /**
   * A URL to an image of the content provider's logo.
   * @member {String} imageUrl
   */
  exports.prototype.imageUrl = undefined;

  /**
   * A list of freetext keywords to describe the content provider.
   * @member {Array.<String>} keywords
   */
  exports.prototype.keywords = undefined;

  /**
   * The date the content provider was first created on TeSS
   * @member {Date} createdAt
   */
  exports.prototype.createdAt = undefined;

  /**
   * The date the content provider was last updated on TeSS
   * @member {Date} updatedAt
   */
  exports.prototype.updatedAt = undefined;


  return exports;

}));
