/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import MultiRelationshipObject from './MultiRelationshipObject';





/**
* The ContentProviderResourceRelationships model module.
* @module model/ContentProviderResourceRelationships
* @version 0.2.0
*/
export default class ContentProviderResourceRelationships {
    /**
    * Constructs a new <code>ContentProviderResourceRelationships</code>.
    * @alias module:model/ContentProviderResourceRelationships
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ContentProviderResourceRelationships</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContentProviderResourceRelationships} obj Optional instance to populate.
    * @return {module:model/ContentProviderResourceRelationships} The populated <code>ContentProviderResourceRelationships</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContentProviderResourceRelationships();

            
            
            

            if (data.hasOwnProperty('events')) {
                obj['events'] = MultiRelationshipObject.constructFromObject(data['events']);
            }
            if (data.hasOwnProperty('materials')) {
                obj['materials'] = MultiRelationshipObject.constructFromObject(data['materials']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/MultiRelationshipObject} events
    */
    events = undefined;
    /**
    * @member {module:model/MultiRelationshipObject} materials
    */
    materials = undefined;








}


