/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ContentProviderResource from './ContentProviderResource';
import JsonApiResponse from './JsonApiResponse';





/**
* The ContentProvider model module.
* @module model/ContentProvider
* @version 0.2.0
*/
export default class ContentProvider {
    /**
    * Constructs a new <code>ContentProvider</code>.
    * @alias module:model/ContentProvider
    * @class
    * @extends module:model/JsonApiResponse
    */

    constructor() {
        

        JsonApiResponse.call(this);
        

        

        
    }

    /**
    * Constructs a <code>ContentProvider</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContentProvider} obj Optional instance to populate.
    * @return {module:model/ContentProvider} The populated <code>ContentProvider</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContentProvider();

            

            JsonApiResponse.constructFromObject(data, obj);
            

            if (data.hasOwnProperty('data')) {
                obj['data'] = ContentProviderResource.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ContentProviderResource} data
    */
    data = undefined;








}


