/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ContentProviderAttributes model module.
* @module model/ContentProviderAttributes
* @version 0.2.0
*/
export default class ContentProviderAttributes {
    /**
    * Constructs a new <code>ContentProviderAttributes</code>.
    * @alias module:model/ContentProviderAttributes
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ContentProviderAttributes</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContentProviderAttributes} obj Optional instance to populate.
    * @return {module:model/ContentProviderAttributes} The populated <code>ContentProviderAttributes</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContentProviderAttributes();

            
            
            

            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('image-url')) {
                obj['image-url'] = ApiClient.convertToType(data['image-url'], 'String');
            }
            if (data.hasOwnProperty('keywords')) {
                obj['keywords'] = ApiClient.convertToType(data['keywords'], ['String']);
            }
            if (data.hasOwnProperty('created-at')) {
                obj['created-at'] = ApiClient.convertToType(data['created-at'], 'Date');
            }
            if (data.hasOwnProperty('updated-at')) {
                obj['updated-at'] = ApiClient.convertToType(data['updated-at'], 'Date');
            }
        }
        return obj;
    }

    /**
    * The \"friendly\" identifier of the content provider.
    * @member {String} slug
    */
    slug = undefined;
    /**
    * The title of the content provider.
    * @member {String} title
    */
    title = undefined;
    /**
    * A description of the content provider.
    * @member {String} description
    */
    description = undefined;
    /**
    * The URL to the content provider's website.
    * @member {String} url
    */
    url = undefined;
    /**
    * A URL to an image of the content provider's logo.
    * @member {String} image-url
    */
    image-url = undefined;
    /**
    * A list of freetext keywords to describe the content provider.
    * @member {Array.<String>} keywords
    */
    keywords = undefined;
    /**
    * The date the content provider was first created on TeSS
    * @member {Date} created-at
    */
    created-at = undefined;
    /**
    * The date the content provider was last updated on TeSS
    * @member {Date} updated-at
    */
    updated-at = undefined;








}


