/**
 * TeSS JSON-API
 * Testing the JSON-API API for TeSS. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ContentProviderResource', 'model/JsonApiResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ContentProviderResource'), require('./JsonApiResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.TessJsonApi) {
      root.TessJsonApi = {};
    }
    root.TessJsonApi.ContentProvider = factory(root.TessJsonApi.ApiClient, root.TessJsonApi.ContentProviderResource, root.TessJsonApi.JsonApiResponse);
  }
}(this, function(ApiClient, ContentProviderResource, JsonApiResponse) {
  'use strict';




  /**
   * The ContentProvider model module.
   * @module model/ContentProvider
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ContentProvider</code>.
   * @alias module:model/ContentProvider
   * @class
   * @extends module:model/JsonApiResponse
   */
  var exports = function() {
    var _this = this;
    JsonApiResponse.call(_this);

  };

  /**
   * Constructs a <code>ContentProvider</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContentProvider} obj Optional instance to populate.
   * @return {module:model/ContentProvider} The populated <code>ContentProvider</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      JsonApiResponse.constructFromObject(data, obj);
      if (data.hasOwnProperty('data')) {
        obj['data'] = ContentProviderResource.constructFromObject(data['data']);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(JsonApiResponse.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {module:model/ContentProviderResource} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


