/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MultiRelationshipObject', 'model/SingleRelationshipObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MultiRelationshipObject'), require('./SingleRelationshipObject'));
  } else {
    // Browser globals (root is window)
    if (!root.TessJsonApi) {
      root.TessJsonApi = {};
    }
    root.TessJsonApi.EventResourceRelationships = factory(root.TessJsonApi.ApiClient, root.TessJsonApi.MultiRelationshipObject, root.TessJsonApi.SingleRelationshipObject);
  }
}(this, function(ApiClient, MultiRelationshipObject, SingleRelationshipObject) {
  'use strict';




  /**
   * The EventResourceRelationships model module.
   * @module model/EventResourceRelationships
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>EventResourceRelationships</code>.
   * @alias module:model/EventResourceRelationships
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>EventResourceRelationships</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventResourceRelationships} obj Optional instance to populate.
   * @return {module:model/EventResourceRelationships} The populated <code>EventResourceRelationships</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('user')) {
        obj['user'] = SingleRelationshipObject.constructFromObject(data['user']);
      }
      if (data.hasOwnProperty('content-provider')) {
        obj['content-provider'] = SingleRelationshipObject.constructFromObject(data['content-provider']);
      }
      if (data.hasOwnProperty('nodes')) {
        obj['nodes'] = MultiRelationshipObject.constructFromObject(data['nodes']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SingleRelationshipObject} user
   */
  exports.prototype['user'] = undefined;
  /**
   * @member {module:model/SingleRelationshipObject} content-provider
   */
  exports.prototype['content-provider'] = undefined;
  /**
   * @member {module:model/MultiRelationshipObject} nodes
   */
  exports.prototype['nodes'] = undefined;



  return exports;
}));


