/*
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EventAttributes', 'model/ResourceObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EventAttributes'), require('./ResourceObject'));
  } else {
    // Browser globals (root is window)
    if (!root.TessJsonApi) {
      root.TessJsonApi = {};
    }
    root.TessJsonApi.EventResource = factory(root.TessJsonApi.ApiClient, root.TessJsonApi.EventAttributes, root.TessJsonApi.ResourceObject);
  }
}(this, function(ApiClient, EventAttributes, ResourceObject) {
  'use strict';

  /**
   * The EventResource model module.
   * @module model/EventResource
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>EventResource</code>.
   * @alias module:model/EventResource
   * @class
   * @extends module:model/ResourceObject
   */
  var exports = function() {
    ResourceObject.call(this);
  };

  /**
   * Constructs a <code>EventResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventResource} obj Optional instance to populate.
   * @return {module:model/EventResource} The populated <code>EventResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ResourceObject.constructFromObject(data, obj);
      if (data.hasOwnProperty('attributes'))
        obj.attributes = EventAttributes.constructFromObject(data['attributes']);
      if (data.hasOwnProperty('relationships'))
        obj.relationships = ApiClient.convertToType(data['relationships'], Object);
      if (data.hasOwnProperty('links'))
        obj.links = ApiClient.convertToType(data['links'], Object);
    }
    return obj;
  }

  exports.prototype = Object.create(ResourceObject.prototype);
  exports.prototype.constructor = exports;
  /**
   * @member {module:model/EventAttributes} attributes
   */
  exports.prototype.attributes = undefined;

  /**
   * @member {Object} relationships
   */
  exports.prototype.relationships = undefined;

  /**
   * @member {Object} links
   */
  exports.prototype.links = undefined;


  return exports;

}));
