/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FacetedCollectionAllOfMeta from './FacetedCollectionAllOfMeta';
import Links from './Links';

/**
 * The FacetedCollectionAllOf model module.
 * @module model/FacetedCollectionAllOf
 * @version 1.4.0
 */
class FacetedCollectionAllOf {
    /**
     * Constructs a new <code>FacetedCollectionAllOf</code>.
     * @alias module:model/FacetedCollectionAllOf
     */
    constructor() { 
        
        FacetedCollectionAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FacetedCollectionAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FacetedCollectionAllOf} obj Optional instance to populate.
     * @return {module:model/FacetedCollectionAllOf} The populated <code>FacetedCollectionAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FacetedCollectionAllOf();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Object]);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = FacetedCollectionAllOfMeta.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], Links);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FacetedCollectionAllOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FacetedCollectionAllOf</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['data'])) {
            throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
        }
        // validate the optional field `meta`
        if (data['meta']) { // data not null
          FacetedCollectionAllOfMeta.validateJSON(data['meta']);
        }
        // validate the optional field `links`
        if (data['links']) { // data not null
          Links.validateJSON(data['links']);
        }

        return true;
    }


}



/**
 * @member {Array.<Object>} data
 */
FacetedCollectionAllOf.prototype['data'] = undefined;

/**
 * @member {module:model/FacetedCollectionAllOfMeta} meta
 */
FacetedCollectionAllOf.prototype['meta'] = undefined;

/**
 * @member {module:model/Links} links
 */
FacetedCollectionAllOf.prototype['links'] = undefined;






export default FacetedCollectionAllOf;

