/*
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/JsonApiResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./JsonApiResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.TessJsonApi) {
      root.TessJsonApi = {};
    }
    root.TessJsonApi.FacetedCollection = factory(root.TessJsonApi.ApiClient, root.TessJsonApi.JsonApiResponse);
  }
}(this, function(ApiClient, JsonApiResponse) {
  'use strict';

  /**
   * The FacetedCollection model module.
   * @module model/FacetedCollection
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>FacetedCollection</code>.
   * @alias module:model/FacetedCollection
   * @class
   * @extends module:model/JsonApiResponse
   */
  var exports = function() {
    JsonApiResponse.call(this);
  };

  /**
   * Constructs a <code>FacetedCollection</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FacetedCollection} obj Optional instance to populate.
   * @return {module:model/FacetedCollection} The populated <code>FacetedCollection</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      JsonApiResponse.constructFromObject(data, obj);
      if (data.hasOwnProperty('meta'))
        obj.meta = ApiClient.convertToType(data['meta'], Object);
      if (data.hasOwnProperty('links'))
        obj.links = ApiClient.convertToType(data['links'], Object);
    }
    return obj;
  }

  exports.prototype = Object.create(JsonApiResponse.prototype);
  exports.prototype.constructor = exports;
  /**
   * @member {Object} meta
   */
  exports.prototype.meta = undefined;

  /**
   * @member {Object} links
   */
  exports.prototype.links = undefined;


  return exports;

}));
