/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventResourceAllOfRelationships from './EventResourceAllOfRelationships';
import Links from './Links';
import MaterialAttributes from './MaterialAttributes';

/**
 * The MaterialResourceAllOf model module.
 * @module model/MaterialResourceAllOf
 * @version 0.2.0
 */
class MaterialResourceAllOf {
    /**
     * Constructs a new <code>MaterialResourceAllOf</code>.
     * @alias module:model/MaterialResourceAllOf
     */
    constructor() { 
        
        MaterialResourceAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MaterialResourceAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MaterialResourceAllOf} obj Optional instance to populate.
     * @return {module:model/MaterialResourceAllOf} The populated <code>MaterialResourceAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MaterialResourceAllOf();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = MaterialAttributes.constructFromObject(data['attributes']);
            }
            if (data.hasOwnProperty('relationships')) {
                obj['relationships'] = EventResourceAllOfRelationships.constructFromObject(data['relationships']);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = Links.constructFromObject(data['links']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MaterialResourceAllOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MaterialResourceAllOf</code>.
     */
    static validateJSON(data) {
        // validate the optional field `attributes`
        if (data['attributes']) { // data not null
          MaterialAttributes.validateJSON(data['attributes']);
        }
        // validate the optional field `relationships`
        if (data['relationships']) { // data not null
          EventResourceAllOfRelationships.validateJSON(data['relationships']);
        }
        // validate the optional field `links`
        if (data['links']) { // data not null
          Links.validateJSON(data['links']);
        }

        return true;
    }


}



/**
 * @member {module:model/MaterialAttributes} attributes
 */
MaterialResourceAllOf.prototype['attributes'] = undefined;

/**
 * @member {module:model/EventResourceAllOfRelationships} relationships
 */
MaterialResourceAllOf.prototype['relationships'] = undefined;

/**
 * @member {module:model/Links} links
 */
MaterialResourceAllOf.prototype['links'] = undefined;






export default MaterialResourceAllOf;

