/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The OntologyTerm model module.
* @module model/OntologyTerm
* @version 0.2.0
*/
export default class OntologyTerm {
    /**
    * Constructs a new <code>OntologyTerm</code>.
    * @alias module:model/OntologyTerm
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>OntologyTerm</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OntologyTerm} obj Optional instance to populate.
    * @return {module:model/OntologyTerm} The populated <code>OntologyTerm</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OntologyTerm();

            
            
            

            if (data.hasOwnProperty('preferred-label')) {
                obj['preferred-label'] = ApiClient.convertToType(data['preferred-label'], 'String');
            }
            if (data.hasOwnProperty('uri')) {
                obj['uri'] = ApiClient.convertToType(data['uri'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} preferred-label
    */
    preferred-label = undefined;
    /**
    * @member {String} uri
    */
    uri = undefined;








}


