/*
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TessJsonApi) {
      root.TessJsonApi = {};
    }
    root.TessJsonApi.PaginationLinks = factory(root.TessJsonApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The PaginationLinks model module.
   * @module model/PaginationLinks
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>PaginationLinks</code>.
   * @alias module:model/PaginationLinks
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PaginationLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaginationLinks} obj Optional instance to populate.
   * @return {module:model/PaginationLinks} The populated <code>PaginationLinks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('prev'))
        obj.prev = ApiClient.convertToType(data['prev'], 'String');
      if (data.hasOwnProperty('next'))
        obj.next = ApiClient.convertToType(data['next'], 'String');
      if (data.hasOwnProperty('first'))
        obj.first = ApiClient.convertToType(data['first'], 'String');
      if (data.hasOwnProperty('last'))
        obj.last = ApiClient.convertToType(data['last'], 'String');
    }
    return obj;
  }

  /**
   * The previous page of the collection.
   * @member {String} prev
   */
  exports.prototype.prev = undefined;

  /**
   * The next page of the collection.
   * @member {String} next
   */
  exports.prototype.next = undefined;

  /**
   * The first page of the collection.
   * @member {String} first
   */
  exports.prototype.first = undefined;

  /**
   * The final page of the collection.
   * @member {String} last
   */
  exports.prototype.last = undefined;


  return exports;

}));
