/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Links from './Links';

/**
 * The ResourceObjectAllOf model module.
 * @module model/ResourceObjectAllOf
 * @version 0.2.0
 */
class ResourceObjectAllOf {
    /**
     * Constructs a new <code>ResourceObjectAllOf</code>.
     * @alias module:model/ResourceObjectAllOf
     */
    constructor() { 
        
        ResourceObjectAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResourceObjectAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResourceObjectAllOf} obj Optional instance to populate.
     * @return {module:model/ResourceObjectAllOf} The populated <code>ResourceObjectAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResourceObjectAllOf();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], Object);
            }
            if (data.hasOwnProperty('relationships')) {
                obj['relationships'] = ApiClient.convertToType(data['relationships'], Object);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = Links.constructFromObject(data['links']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResourceObjectAllOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResourceObjectAllOf</code>.
     */
    static validateJSON(data) {
        // validate the optional field `links`
        if (data['links']) { // data not null
          Links.validateJSON(data['links']);
        }

        return true;
    }


}



/**
 * @member {Object} attributes
 */
ResourceObjectAllOf.prototype['attributes'] = undefined;

/**
 * @member {Object} relationships
 */
ResourceObjectAllOf.prototype['relationships'] = undefined;

/**
 * @member {module:model/Links} links
 */
ResourceObjectAllOf.prototype['links'] = undefined;






export default ResourceObjectAllOf;

