/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ResourceIdentifierObject model module.
* @module model/ResourceIdentifierObject
* @version 0.2.0
*/
export default class ResourceIdentifierObject {
    /**
    * Constructs a new <code>ResourceIdentifierObject</code>.
    * @alias module:model/ResourceIdentifierObject
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ResourceIdentifierObject</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ResourceIdentifierObject} obj Optional instance to populate.
    * @return {module:model/ResourceIdentifierObject} The populated <code>ResourceIdentifierObject</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResourceIdentifierObject();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} type
    */
    type = undefined;
    /**
    * @member {Object} meta
    */
    meta = undefined;








}


