/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ResourceIdentifierObject from './ResourceIdentifierObject';





/**
* The SingleRelationshipObject model module.
* @module model/SingleRelationshipObject
* @version 0.2.0
*/
export default class SingleRelationshipObject {
    /**
    * Constructs a new <code>SingleRelationshipObject</code>.
    * @alias module:model/SingleRelationshipObject
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>SingleRelationshipObject</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SingleRelationshipObject} obj Optional instance to populate.
    * @return {module:model/SingleRelationshipObject} The populated <code>SingleRelationshipObject</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SingleRelationshipObject();

            
            
            

            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], Object);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ResourceIdentifierObject.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {Object} links
    */
    links = undefined;
    /**
    * @member {module:model/ResourceIdentifierObject} data
    */
    data = undefined;
    /**
    * @member {Object} meta
    */
    meta = undefined;








}


