/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JsonApiResponse from './JsonApiResponse';
import UserCollectionAllOf from './UserCollectionAllOf';
import UserResource from './UserResource';

/**
 * The UserCollection model module.
 * @module model/UserCollection
 * @version 1.4.0
 */
class UserCollection {
    /**
     * Constructs a new <code>UserCollection</code>.
     * @alias module:model/UserCollection
     * @implements module:model/JsonApiResponse
     * @implements module:model/UserCollectionAllOf
     */
    constructor() { 
        JsonApiResponse.initialize(this);UserCollectionAllOf.initialize(this);
        UserCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserCollection} obj Optional instance to populate.
     * @return {module:model/UserCollection} The populated <code>UserCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserCollection();
            JsonApiResponse.constructFromObject(data, obj);
            UserCollectionAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], Object);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], Object);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], Object);
            }
            if (data.hasOwnProperty('included')) {
                obj['included'] = ApiClient.convertToType(data['included'], Object);
            }
            if (data.hasOwnProperty('jsonapi')) {
                obj['jsonapi'] = ApiClient.convertToType(data['jsonapi'], Object);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [UserResource]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserCollection</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserCollection</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                UserResource.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * @member {Object} errors
 */
UserCollection.prototype['errors'] = undefined;

/**
 * @member {Object} meta
 */
UserCollection.prototype['meta'] = undefined;

/**
 * @member {Object} links
 */
UserCollection.prototype['links'] = undefined;

/**
 * @member {Object} included
 */
UserCollection.prototype['included'] = undefined;

/**
 * @member {Object} jsonapi
 */
UserCollection.prototype['jsonapi'] = undefined;

/**
 * @member {Array.<module:model/UserResource>} data
 */
UserCollection.prototype['data'] = undefined;


// Implement JsonApiResponse interface:
/**
 * @member {Object} errors
 */
JsonApiResponse.prototype['errors'] = undefined;
/**
 * @member {Object} meta
 */
JsonApiResponse.prototype['meta'] = undefined;
/**
 * @member {Object} links
 */
JsonApiResponse.prototype['links'] = undefined;
/**
 * @member {Object} included
 */
JsonApiResponse.prototype['included'] = undefined;
/**
 * @member {Object} jsonapi
 */
JsonApiResponse.prototype['jsonapi'] = undefined;
// Implement UserCollectionAllOf interface:
/**
 * @member {Array.<module:model/UserResource>} data
 */
UserCollectionAllOf.prototype['data'] = undefined;




export default UserCollection;

