/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Links from './Links';
import UserAttributes from './UserAttributes';

/**
 * The UserResourceAllOf model module.
 * @module model/UserResourceAllOf
 * @version 0.2.0
 */
class UserResourceAllOf {
    /**
     * Constructs a new <code>UserResourceAllOf</code>.
     * @alias module:model/UserResourceAllOf
     */
    constructor() { 
        
        UserResourceAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserResourceAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserResourceAllOf} obj Optional instance to populate.
     * @return {module:model/UserResourceAllOf} The populated <code>UserResourceAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserResourceAllOf();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = UserAttributes.constructFromObject(data['attributes']);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = Links.constructFromObject(data['links']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserResourceAllOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserResourceAllOf</code>.
     */
    static validateJSON(data) {
        // validate the optional field `attributes`
        if (data['attributes']) { // data not null
          UserAttributes.validateJSON(data['attributes']);
        }
        // validate the optional field `links`
        if (data['links']) { // data not null
          Links.validateJSON(data['links']);
        }

        return true;
    }


}



/**
 * @member {module:model/UserAttributes} attributes
 */
UserResourceAllOf.prototype['attributes'] = undefined;

/**
 * @member {module:model/Links} links
 */
UserResourceAllOf.prototype['links'] = undefined;






export default UserResourceAllOf;

