/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JsonApiResponse from './JsonApiResponse';
import WorkflowResource from './WorkflowResource';

/**
 * The Workflow model module.
 * @module model/Workflow
 * @version 1.4.0
 */
class Workflow {
    /**
     * Constructs a new <code>Workflow</code>.
     * @alias module:model/Workflow
     * @implements module:model/JsonApiResponse
     */
    constructor() { 
        JsonApiResponse.initialize(this);
        Workflow.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Workflow</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Workflow} obj Optional instance to populate.
     * @return {module:model/Workflow} The populated <code>Workflow</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Workflow();
            JsonApiResponse.constructFromObject(data, obj);

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], Object);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], Object);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], Object);
            }
            if (data.hasOwnProperty('included')) {
                obj['included'] = ApiClient.convertToType(data['included'], Object);
            }
            if (data.hasOwnProperty('jsonapi')) {
                obj['jsonapi'] = ApiClient.convertToType(data['jsonapi'], Object);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = WorkflowResource.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Workflow</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Workflow</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          WorkflowResource.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {Object} errors
 */
Workflow.prototype['errors'] = undefined;

/**
 * @member {Object} meta
 */
Workflow.prototype['meta'] = undefined;

/**
 * @member {Object} links
 */
Workflow.prototype['links'] = undefined;

/**
 * @member {Object} included
 */
Workflow.prototype['included'] = undefined;

/**
 * @member {Object} jsonapi
 */
Workflow.prototype['jsonapi'] = undefined;

/**
 * @member {module:model/WorkflowResource} data
 */
Workflow.prototype['data'] = undefined;


// Implement JsonApiResponse interface:
/**
 * @member {Object} errors
 */
JsonApiResponse.prototype['errors'] = undefined;
/**
 * @member {Object} meta
 */
JsonApiResponse.prototype['meta'] = undefined;
/**
 * @member {Object} links
 */
JsonApiResponse.prototype['links'] = undefined;
/**
 * @member {Object} included
 */
JsonApiResponse.prototype['included'] = undefined;
/**
 * @member {Object} jsonapi
 */
JsonApiResponse.prototype['jsonapi'] = undefined;




export default Workflow;

