/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ResourceObject', 'model/WorkflowAttributes', 'model/WorkflowResourceRelationships'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ResourceObject'), require('./WorkflowAttributes'), require('./WorkflowResourceRelationships'));
  } else {
    // Browser globals (root is window)
    if (!root.TessJsonApi) {
      root.TessJsonApi = {};
    }
    root.TessJsonApi.WorkflowResource = factory(root.TessJsonApi.ApiClient, root.TessJsonApi.ResourceObject, root.TessJsonApi.WorkflowAttributes, root.TessJsonApi.WorkflowResourceRelationships);
  }
}(this, function(ApiClient, ResourceObject, WorkflowAttributes, WorkflowResourceRelationships) {
  'use strict';




  /**
   * The WorkflowResource model module.
   * @module model/WorkflowResource
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>WorkflowResource</code>.
   * @alias module:model/WorkflowResource
   * @class
   * @extends module:model/ResourceObject
   */
  var exports = function() {
    var _this = this;
    ResourceObject.call(_this);



  };

  /**
   * Constructs a <code>WorkflowResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorkflowResource} obj Optional instance to populate.
   * @return {module:model/WorkflowResource} The populated <code>WorkflowResource</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ResourceObject.constructFromObject(data, obj);
      if (data.hasOwnProperty('attributes')) {
        obj['attributes'] = WorkflowAttributes.constructFromObject(data['attributes']);
      }
      if (data.hasOwnProperty('relationships')) {
        obj['relationships'] = WorkflowResourceRelationships.constructFromObject(data['relationships']);
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], Object);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(ResourceObject.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {module:model/WorkflowAttributes} attributes
   */
  exports.prototype['attributes'] = undefined;
  /**
   * @member {module:model/WorkflowResourceRelationships} relationships
   */
  exports.prototype['relationships'] = undefined;
  /**
   * @member {Object} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


