/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import SingleRelationshipObject from './SingleRelationshipObject';





/**
* The WorkflowResourceRelationships model module.
* @module model/WorkflowResourceRelationships
* @version 0.2.0
*/
export default class WorkflowResourceRelationships {
    /**
    * Constructs a new <code>WorkflowResourceRelationships</code>.
    * @alias module:model/WorkflowResourceRelationships
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>WorkflowResourceRelationships</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WorkflowResourceRelationships} obj Optional instance to populate.
    * @return {module:model/WorkflowResourceRelationships} The populated <code>WorkflowResourceRelationships</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowResourceRelationships();

            
            
            

            if (data.hasOwnProperty('user')) {
                obj['user'] = SingleRelationshipObject.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/SingleRelationshipObject} user
    */
    user = undefined;








}


