/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import FacetedCollection from './FacetedCollection';
import FacetedCollectionMeta from './FacetedCollectionMeta';
import WorkflowResource from './WorkflowResource';





/**
* The WorkflowCollection model module.
* @module model/WorkflowCollection
* @version 0.2.0
*/
export default class WorkflowCollection {
    /**
    * Constructs a new <code>WorkflowCollection</code>.
    * @alias module:model/WorkflowCollection
    * @class
    * @extends module:model/FacetedCollection
    */

    constructor() {
        

        FacetedCollection.call(this);
        

        

        
    }

    /**
    * Constructs a <code>WorkflowCollection</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WorkflowCollection} obj Optional instance to populate.
    * @return {module:model/WorkflowCollection} The populated <code>WorkflowCollection</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowCollection();

            

            FacetedCollection.constructFromObject(data, obj);
            

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [WorkflowResource]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/WorkflowResource>} data
    */
    data = undefined;








}


