/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.11
 *
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Event', 'model/EventCollection'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Event'), require('../model/EventCollection'));
  } else {
    // Browser globals (root is window)
    if (!root.TessJsonApi) {
      root.TessJsonApi = {};
    }
    root.TessJsonApi.EventsApi = factory(root.TessJsonApi.ApiClient, root.TessJsonApi.Event, root.TessJsonApi.EventCollection);
  }
}(this, function(ApiClient, Event, EventCollection) {
  'use strict';

  /**
   * Events service.
   * @module api/EventsApi
   * @version 0.1.0
   */

  /**
   * Constructs a new EventsApi. 
   * @alias module:api/EventsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the eventsGet operation.
     * @callback module:api/EventsApi~eventsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EventCollection} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.q Search keywords.
     * @param {Number} opts.pageNumber The page of the collection to view. (default to 1)
     * @param {Number} opts.pageSize The number of results to return per page. (default to 30)
     * @param {module:model/String} opts.sort Sort order:  * default - sort by date (for Events), sort by number of resources (for Content Providers) otherwise sort by title (default).  * new - Sort by when the entry was created.  * mod - Sort by when the entry was last modified.  * rel - Sort by search query relevance.  * early - Sort by date, earliest to latest (Events only).  * late - Sort by date, latest to earliest (Events only). 
     * @param {Array.<String>} opts.contentProvider Filter by content provider name.
     * @param {Array.<String>} opts.keywords Filter by keywords.
     * @param {Array.<String>} opts.node Filter by ELIXIR node name.
     * @param {Array.<String>} opts.scientificTopics Filter by scientific topics.
     * @param {Array.<String>} opts.targetAudience Filter by who the intended target audience is.
     * @param {Array.<String>} opts.tools Filter by what tools are involved.
     * @param {Array.<module:model/String>} opts.eventTypes Filter by event type.
     * @param {Array.<String>} opts.city Filter by city.
     * @param {Array.<String>} opts.country Filter by country.
     * @param {Array.<String>} opts.venue Filter by venue
     * @param {Array.<String>} opts.organizer Filter by organizer.
     * @param {Boolean} opts.online Only show online events?
     * @param {Array.<String>} opts.sponsor Filter by sponsor.
     * @param {Boolean} opts.includeExpired Include events that have finished.
     * @param {module:api/EventsApi~eventsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EventCollection}
     */
    this.eventsGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'q': opts['q'],
        'page_number': opts['pageNumber'],
        'page_size': opts['pageSize'],
        'sort': opts['sort'],
        'online': opts['online'],
        'include_expired': opts['includeExpired'],
      };
      var collectionQueryParams = {
        'content_provider[]': {
          value: opts['contentProvider'],
          collectionFormat: 'multi'
        },
        'keywords[]': {
          value: opts['keywords'],
          collectionFormat: 'multi'
        },
        'node[]': {
          value: opts['node'],
          collectionFormat: 'multi'
        },
        'scientific_topics[]': {
          value: opts['scientificTopics'],
          collectionFormat: 'multi'
        },
        'target_audience[]': {
          value: opts['targetAudience'],
          collectionFormat: 'multi'
        },
        'tools[]': {
          value: opts['tools'],
          collectionFormat: 'multi'
        },
        'event_types[]': {
          value: opts['eventTypes'],
          collectionFormat: 'multi'
        },
        'city[]': {
          value: opts['city'],
          collectionFormat: 'multi'
        },
        'country[]': {
          value: opts['country'],
          collectionFormat: 'multi'
        },
        'venue[]': {
          value: opts['venue'],
          collectionFormat: 'multi'
        },
        'organizer[]': {
          value: opts['organizer'],
          collectionFormat: 'multi'
        },
        'sponsor[]': {
          value: opts['sponsor'],
          collectionFormat: 'multi'
        },
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/vnd.api+json'];
      var accepts = ['application/vnd.api+json'];
      var returnType = EventCollection;

      return this.apiClient.callApi(
        '/events', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the eventsSlugGet operation.
     * @callback module:api/EventsApi~eventsSlugGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Event} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} slug The _slug_ id of an event e.g. python-training-2017
     * @param {module:api/EventsApi~eventsSlugGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Event}
     */
    this.eventsSlugGet = function(slug, callback) {
      var postBody = null;

      // verify the required parameter 'slug' is set
      if (slug === undefined || slug === null) {
        throw new Error("Missing the required parameter 'slug' when calling eventsSlugGet");
      }


      var pathParams = {
        'slug': slug
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/vnd.api+json'];
      var accepts = ['application/vnd.api+json'];
      var returnType = Event;

      return this.apiClient.callApi(
        '/events/{slug}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
