/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Material from '../model/Material';
import MaterialCollection from '../model/MaterialCollection';

/**
* Materials service.
* @module api/MaterialsApi
* @version 0.2.0
*/
export default class MaterialsApi {

    /**
    * Constructs a new MaterialsApi. 
    * @alias module:api/MaterialsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the materialsGet operation.
     * @callback module:api/MaterialsApi~materialsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MaterialCollection} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.q Search keywords.
     * @param {Number} opts.pageNumber The page of the collection to view. (default to 1)
     * @param {Number} opts.pageSize The number of results to return per page. (default to 30)
     * @param {module:model/String} opts.sort Sort order:  * default - sort by date (for Events), sort by number of resources (for Content Providers) otherwise sort by title (default).  * new - Sort by when the entry was created.  * mod - Sort by when the entry was last modified.  * rel - Sort by search query relevance.  * early - Sort by date, earliest to latest (Events only).  * late - Sort by date, latest to earliest (Events only). 
     * @param {Array.<String>} opts.authors Filter by author.
     * @param {Array.<String>} opts.contentProvider Filter by content provider name.
     * @param {Array.<String>} opts.contributors Filter by contributor.
     * @param {Array.<module:model/String>} opts.difficultyLevel Filter by difficulty level.
     * @param {Array.<String>} opts.keywords Filter by keywords.
     * @param {Array.<String>} opts.licence Filter by licence. See http://licenses.opendefinition.org/licenses/groups/all.json
     * @param {Array.<String>} opts.node Filter by ELIXIR node name.
     * @param {Array.<String>} opts.scientificTopics Filter by scientific topics.
     * @param {Array.<String>} opts.operations Filter by operations.
     * @param {Array.<String>} opts.targetAudience Filter by who the intended target audience is.
     * @param {Array.<String>} opts.tools Filter by what tools are involved.
     * @param {Array.<String>} opts.resourceType Filter by resource type, e.g. \&quot;Lecture\&quot; etc.
     * @param {module:api/MaterialsApi~materialsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MaterialCollection}
     */
    materialsGet(opts, callback) {
      opts = opts || {};
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
        'q': opts['q'],
        'page_number': opts['pageNumber'],
        'page_size': opts['pageSize'],
        'sort': opts['sort'],
        'authors[]': this.apiClient.buildCollectionParam(opts['authors'], 'multi'),
        'content_provider[]': this.apiClient.buildCollectionParam(opts['contentProvider'], 'multi'),
        'contributors[]': this.apiClient.buildCollectionParam(opts['contributors'], 'multi'),
        'difficulty_level[]': this.apiClient.buildCollectionParam(opts['difficultyLevel'], 'multi'),
        'keywords[]': this.apiClient.buildCollectionParam(opts['keywords'], 'multi'),
        'licence[]': this.apiClient.buildCollectionParam(opts['licence'], 'multi'),
        'node[]': this.apiClient.buildCollectionParam(opts['node'], 'multi'),
        'scientific_topics[]': this.apiClient.buildCollectionParam(opts['scientificTopics'], 'multi'),
        'operations[]': this.apiClient.buildCollectionParam(opts['operations'], 'multi'),
        'target_audience[]': this.apiClient.buildCollectionParam(opts['targetAudience'], 'multi'),
        'tools[]': this.apiClient.buildCollectionParam(opts['tools'], 'multi'),
        'resource_type[]': this.apiClient.buildCollectionParam(opts['resourceType'], 'multi')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/vnd.api+json'];
      let accepts = ['application/vnd.api+json'];
      let returnType = MaterialCollection;

      return this.apiClient.callApi(
        '/materials', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the materialsSlugGet operation.
     * @callback module:api/MaterialsApi~materialsSlugGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Material} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} slug The _slug_ id of an material e.g. python-tutorial
     * @param {module:api/MaterialsApi~materialsSlugGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Material}
     */
    materialsSlugGet(slug, callback) {
      let postBody = null;

      // verify the required parameter 'slug' is set
      if (slug === undefined || slug === null) {
        throw new Error("Missing the required parameter 'slug' when calling materialsSlugGet");
      }


      let pathParams = {
        'slug': slug
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/vnd.api+json'];
      let accepts = ['application/vnd.api+json'];
      let returnType = Material;

      return this.apiClient.callApi(
        '/materials/{slug}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
