/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TessJsonApi);
  }
}(this, function(expect, TessJsonApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TessJsonApi.EventAttributesReport();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventAttributesReport', function() {
    it('should create an instance of EventAttributesReport', function() {
      // uncomment below and update the code to test EventAttributesReport
      //var instance = new TessJsonApi.EventAttributesReport();
      //expect(instance).to.be.a(TessJsonApi.EventAttributesReport);
    });

    it('should have the property funding (base name: "funding")', function() {
      // uncomment below and update the code to test the property funding
      //var instance = new TessJsonApi.EventAttributesReport();
      //expect(instance).to.be();
    });

    it('should have the property attendeeCount (base name: "attendee_count")', function() {
      // uncomment below and update the code to test the property attendeeCount
      //var instance = new TessJsonApi.EventAttributesReport();
      //expect(instance).to.be();
    });

    it('should have the property applicantCount (base name: "applicant_count")', function() {
      // uncomment below and update the code to test the property applicantCount
      //var instance = new TessJsonApi.EventAttributesReport();
      //expect(instance).to.be();
    });

    it('should have the property trainerCount (base name: "trainer_count")', function() {
      // uncomment below and update the code to test the property trainerCount
      //var instance = new TessJsonApi.EventAttributesReport();
      //expect(instance).to.be();
    });

    it('should have the property feedback (base name: "feedback")', function() {
      // uncomment below and update the code to test the property feedback
      //var instance = new TessJsonApi.EventAttributesReport();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instance = new TessJsonApi.EventAttributesReport();
      //expect(instance).to.be();
    });

  });

}));
