/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TessJsonApi);
  }
}(this, function(expect, TessJsonApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TessJsonApi.FacetedCollectionAllOfMeta();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FacetedCollectionAllOfMeta', function() {
    it('should create an instance of FacetedCollectionAllOfMeta', function() {
      // uncomment below and update the code to test FacetedCollectionAllOfMeta
      //var instance = new TessJsonApi.FacetedCollectionAllOfMeta();
      //expect(instance).to.be.a(TessJsonApi.FacetedCollectionAllOfMeta);
    });

    it('should have the property resultsCount (base name: "results-count")', function() {
      // uncomment below and update the code to test the property resultsCount
      //var instance = new TessJsonApi.FacetedCollectionAllOfMeta();
      //expect(instance).to.be();
    });

    it('should have the property query (base name: "query")', function() {
      // uncomment below and update the code to test the property query
      //var instance = new TessJsonApi.FacetedCollectionAllOfMeta();
      //expect(instance).to.be();
    });

    it('should have the property facets (base name: "facets")', function() {
      // uncomment below and update the code to test the property facets
      //var instance = new TessJsonApi.FacetedCollectionAllOfMeta();
      //expect(instance).to.be();
    });

    it('should have the property availableFacets (base name: "available-facets")', function() {
      // uncomment below and update the code to test the property availableFacets
      //var instance = new TessJsonApi.FacetedCollectionAllOfMeta();
      //expect(instance).to.be();
    });

  });

}));
