/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TessJsonApi);
  }
}(this, function(expect, TessJsonApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TessJsonApi.MaterialResourceAllOfRelationships();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MaterialResourceAllOfRelationships', function() {
    it('should create an instance of MaterialResourceAllOfRelationships', function() {
      // uncomment below and update the code to test MaterialResourceAllOfRelationships
      //var instance = new TessJsonApi.MaterialResourceAllOfRelationships();
      //expect(instance).to.be.a(TessJsonApi.MaterialResourceAllOfRelationships);
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instance = new TessJsonApi.MaterialResourceAllOfRelationships();
      //expect(instance).to.be();
    });

    it('should have the property contentProvider (base name: "content-provider")', function() {
      // uncomment below and update the code to test the property contentProvider
      //var instance = new TessJsonApi.MaterialResourceAllOfRelationships();
      //expect(instance).to.be();
    });

    it('should have the property nodes (base name: "nodes")', function() {
      // uncomment below and update the code to test the property nodes
      //var instance = new TessJsonApi.MaterialResourceAllOfRelationships();
      //expect(instance).to.be();
    });

    it('should have the property collections (base name: "collections")', function() {
      // uncomment below and update the code to test the property collections
      //var instance = new TessJsonApi.MaterialResourceAllOfRelationships();
      //expect(instance).to.be();
    });

    it('should have the property events (base name: "events")', function() {
      // uncomment below and update the code to test the property events
      //var instance = new TessJsonApi.MaterialResourceAllOfRelationships();
      //expect(instance).to.be();
    });

  });

}));
