/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TessJsonApi);
  }
}(this, function(expect, TessJsonApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TessJsonApi.NodeAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NodeAttributes', function() {
    it('should create an instance of NodeAttributes', function() {
      // uncomment below and update the code to test NodeAttributes
      //var instance = new TessJsonApi.NodeAttributes();
      //expect(instance).to.be.a(TessJsonApi.NodeAttributes);
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instance = new TessJsonApi.NodeAttributes();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new TessJsonApi.NodeAttributes();
      //expect(instance).to.be();
    });

    it('should have the property memberStatus (base name: "member-status")', function() {
      // uncomment below and update the code to test the property memberStatus
      //var instance = new TessJsonApi.NodeAttributes();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "country-code")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instance = new TessJsonApi.NodeAttributes();
      //expect(instance).to.be();
    });

    it('should have the property homePage (base name: "home-page")', function() {
      // uncomment below and update the code to test the property homePage
      //var instance = new TessJsonApi.NodeAttributes();
      //expect(instance).to.be();
    });

    it('should have the property staff (base name: "staff")', function() {
      // uncomment below and update the code to test the property staff
      //var instance = new TessJsonApi.NodeAttributes();
      //expect(instance).to.be();
    });

    it('should have the property twitter (base name: "twitter")', function() {
      // uncomment below and update the code to test the property twitter
      //var instance = new TessJsonApi.NodeAttributes();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created-at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new TessJsonApi.NodeAttributes();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated-at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new TessJsonApi.NodeAttributes();
      //expect(instance).to.be();
    });

  });

}));
