/**
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ContentProvider from './model/ContentProvider';
import ContentProviderAttributes from './model/ContentProviderAttributes';
import ContentProviderCollection from './model/ContentProviderCollection';
import ContentProviderResource from './model/ContentProviderResource';
import ContentProviderResourceRelationships from './model/ContentProviderResourceRelationships';
import Event from './model/Event';
import EventAttributes from './model/EventAttributes';
import EventAttributesReport from './model/EventAttributesReport';
import EventCollection from './model/EventCollection';
import EventResource from './model/EventResource';
import EventResourceRelationships from './model/EventResourceRelationships';
import ExternalResource from './model/ExternalResource';
import Facet from './model/Facet';
import FacetedCollection from './model/FacetedCollection';
import FacetedCollectionMeta from './model/FacetedCollectionMeta';
import JsonApiResponse from './model/JsonApiResponse';
import Links from './model/Links';
import Material from './model/Material';
import MaterialAttributes from './model/MaterialAttributes';
import MaterialCollection from './model/MaterialCollection';
import MaterialResource from './model/MaterialResource';
import MultiRelationshipObject from './model/MultiRelationshipObject';
import OntologyTerm from './model/OntologyTerm';
import PaginationLinks from './model/PaginationLinks';
import ResourceIdentifierObject from './model/ResourceIdentifierObject';
import ResourceObject from './model/ResourceObject';
import SingleRelationshipObject from './model/SingleRelationshipObject';
import User from './model/User';
import UserAttributes from './model/UserAttributes';
import UserCollection from './model/UserCollection';
import UserResource from './model/UserResource';
import Workflow from './model/Workflow';
import WorkflowAttributes from './model/WorkflowAttributes';
import WorkflowCollection from './model/WorkflowCollection';
import WorkflowResource from './model/WorkflowResource';
import WorkflowResourceRelationships from './model/WorkflowResourceRelationships';
import ContentProvidersApi from './api/ContentProvidersApi';
import EventsApi from './api/EventsApi';
import MaterialsApi from './api/MaterialsApi';
import UsersApi from './api/UsersApi';
import WorkflowsApi from './api/WorkflowsApi';


/**
* An_implementation_of_the_API_for_ELIXIRs_TeSS_following_JSON_API__httpjsonapi_org_standards_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TessJsonApi = require('index'); // See note below*.
* var xxxSvc = new TessJsonApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TessJsonApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TessJsonApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TessJsonApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.2.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ContentProvider model constructor.
     * @property {module:model/ContentProvider}
     */
    ContentProvider,

    /**
     * The ContentProviderAttributes model constructor.
     * @property {module:model/ContentProviderAttributes}
     */
    ContentProviderAttributes,

    /**
     * The ContentProviderCollection model constructor.
     * @property {module:model/ContentProviderCollection}
     */
    ContentProviderCollection,

    /**
     * The ContentProviderResource model constructor.
     * @property {module:model/ContentProviderResource}
     */
    ContentProviderResource,

    /**
     * The ContentProviderResourceRelationships model constructor.
     * @property {module:model/ContentProviderResourceRelationships}
     */
    ContentProviderResourceRelationships,

    /**
     * The Event model constructor.
     * @property {module:model/Event}
     */
    Event,

    /**
     * The EventAttributes model constructor.
     * @property {module:model/EventAttributes}
     */
    EventAttributes,

    /**
     * The EventAttributesReport model constructor.
     * @property {module:model/EventAttributesReport}
     */
    EventAttributesReport,

    /**
     * The EventCollection model constructor.
     * @property {module:model/EventCollection}
     */
    EventCollection,

    /**
     * The EventResource model constructor.
     * @property {module:model/EventResource}
     */
    EventResource,

    /**
     * The EventResourceRelationships model constructor.
     * @property {module:model/EventResourceRelationships}
     */
    EventResourceRelationships,

    /**
     * The ExternalResource model constructor.
     * @property {module:model/ExternalResource}
     */
    ExternalResource,

    /**
     * The Facet model constructor.
     * @property {module:model/Facet}
     */
    Facet,

    /**
     * The FacetedCollection model constructor.
     * @property {module:model/FacetedCollection}
     */
    FacetedCollection,

    /**
     * The FacetedCollectionMeta model constructor.
     * @property {module:model/FacetedCollectionMeta}
     */
    FacetedCollectionMeta,

    /**
     * The JsonApiResponse model constructor.
     * @property {module:model/JsonApiResponse}
     */
    JsonApiResponse,

    /**
     * The Links model constructor.
     * @property {module:model/Links}
     */
    Links,

    /**
     * The Material model constructor.
     * @property {module:model/Material}
     */
    Material,

    /**
     * The MaterialAttributes model constructor.
     * @property {module:model/MaterialAttributes}
     */
    MaterialAttributes,

    /**
     * The MaterialCollection model constructor.
     * @property {module:model/MaterialCollection}
     */
    MaterialCollection,

    /**
     * The MaterialResource model constructor.
     * @property {module:model/MaterialResource}
     */
    MaterialResource,

    /**
     * The MultiRelationshipObject model constructor.
     * @property {module:model/MultiRelationshipObject}
     */
    MultiRelationshipObject,

    /**
     * The OntologyTerm model constructor.
     * @property {module:model/OntologyTerm}
     */
    OntologyTerm,

    /**
     * The PaginationLinks model constructor.
     * @property {module:model/PaginationLinks}
     */
    PaginationLinks,

    /**
     * The ResourceIdentifierObject model constructor.
     * @property {module:model/ResourceIdentifierObject}
     */
    ResourceIdentifierObject,

    /**
     * The ResourceObject model constructor.
     * @property {module:model/ResourceObject}
     */
    ResourceObject,

    /**
     * The SingleRelationshipObject model constructor.
     * @property {module:model/SingleRelationshipObject}
     */
    SingleRelationshipObject,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserAttributes model constructor.
     * @property {module:model/UserAttributes}
     */
    UserAttributes,

    /**
     * The UserCollection model constructor.
     * @property {module:model/UserCollection}
     */
    UserCollection,

    /**
     * The UserResource model constructor.
     * @property {module:model/UserResource}
     */
    UserResource,

    /**
     * The Workflow model constructor.
     * @property {module:model/Workflow}
     */
    Workflow,

    /**
     * The WorkflowAttributes model constructor.
     * @property {module:model/WorkflowAttributes}
     */
    WorkflowAttributes,

    /**
     * The WorkflowCollection model constructor.
     * @property {module:model/WorkflowCollection}
     */
    WorkflowCollection,

    /**
     * The WorkflowResource model constructor.
     * @property {module:model/WorkflowResource}
     */
    WorkflowResource,

    /**
     * The WorkflowResourceRelationships model constructor.
     * @property {module:model/WorkflowResourceRelationships}
     */
    WorkflowResourceRelationships,

    /**
    * The ContentProvidersApi service constructor.
    * @property {module:api/ContentProvidersApi}
    */
    ContentProvidersApi,

    /**
    * The EventsApi service constructor.
    * @property {module:api/EventsApi}
    */
    EventsApi,

    /**
    * The MaterialsApi service constructor.
    * @property {module:api/MaterialsApi}
    */
    MaterialsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi,

    /**
    * The WorkflowsApi service constructor.
    * @property {module:api/WorkflowsApi}
    */
    WorkflowsApi
};
