/*
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TessJsonApi);
  }
}(this, function(expect, TessJsonApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TessJsonApi.EventsApi();
  });

  describe('(package)', function() {
    describe('EventsApi', function() {
      describe('eventsGet', function() {
        it('should call eventsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for eventsGet call and complete the assertions
          /*
          var opts = {};
          opts.q = "q_example";
          opts.pageNumber = 1;
          opts.pageSize = 30;
          opts.sort = "sort_example";
          opts.contentProvider = ["contentProvider_example"];
          opts.keywords = ["keywords_example"];
          opts.node = ["node_example"];
          opts.scientificTopics = ["scientificTopics_example"];
          opts.operations = ["operations_example"];
          opts.targetAudience = ["targetAudience_example"];
          opts.tools = ["tools_example"];
          opts.eventTypes = ["eventTypes_example"];
          opts.city = ["city_example"];
          opts.country = ["country_example"];
          opts.venue = ["venue_example"];
          opts.organizer = ["organizer_example"];
          opts.online = true;
          opts.sponsor = ["sponsor_example"];
          opts.includeExpired = true;

          instance.eventsGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TessJsonApi.EventCollection);
            expect(data.errors).to.be.a(Object);
            expect(data.errors).to.be();
            expect(data.meta).to.be.a(Object);
            expect(data.meta).to.be();
            expect(data.links).to.be.a(Object);
            expect(data.links).to.be();
            expect(data.included).to.be.a(Object);
            expect(data.included).to.be();
            expect(data.jsonapi).to.be.a(Object);
            expect(data.jsonapi).to.be();
            {
              let dataCtr = data.data;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(TessJsonApi.EventResource);
                expect(data.id).to.be.a('string');
                expect(data.id).to.be("");
                expect(data.type).to.be.a('string');
                expect(data.type).to.be("");
                expect(data.meta).to.be.a(Object);
                expect(data.meta).to.be();
                expect(data.attributes).to.be.a(TessJsonApi.EventAttributes);
                      expect(data.attributes.slug).to.be.a('string');
                  expect(data.attributes.slug).to.be("");
                  expect(data.attributes.title).to.be.a('string');
                  expect(data.attributes.title).to.be("");
                  expect(data.attributes.subtitle).to.be.a('string');
                  expect(data.attributes.subtitle).to.be("");
                  expect(data.attributes.url).to.be.a('string');
                  expect(data.attributes.url).to.be("");
                  expect(data.attributes.organizer).to.be.a('string');
                  expect(data.attributes.organizer).to.be("");
                  expect(data.attributes.description).to.be.a('string');
                  expect(data.attributes.description).to.be("");
                  expect(data.attributes.start).to.be.a(Date);
                  expect(data.attributes.start).to.be(new Date());
                  expect(data.attributes.end).to.be.a(Date);
                  expect(data.attributes.end).to.be(new Date());
                  expect(data.attributes.sponsor).to.be.a('string');
                  expect(data.attributes.sponsor).to.be("");
                  expect(data.attributes.venue).to.be.a('string');
                  expect(data.attributes.venue).to.be("");
                  expect(data.attributes.city).to.be.a('string');
                  expect(data.attributes.city).to.be("");
                  expect(data.attributes.country).to.be.a('string');
                  expect(data.attributes.country).to.be("");
                  expect(data.attributes.county).to.be.a('string');
                  expect(data.attributes.county).to.be("");
                  expect(data.attributes.postcode).to.be.a('string');
                  expect(data.attributes.postcode).to.be("");
                  expect(data.attributes.latitude).to.be.a('string');
                  expect(data.attributes.latitude).to.be("");
                  expect(data.attributes.longitude).to.be.a('string');
                  expect(data.attributes.longitude).to.be("");
                  expect(data.attributes.createdAt).to.be.a(Date);
                  expect(data.attributes.createdAt).to.be(new Date());
                  expect(data.attributes.updatedAt).to.be.a(Date);
                  expect(data.attributes.updatedAt).to.be(new Date());
                  {
                    let dataCtr = data.attributes.keywords;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a('string');
                      expect(data).to.be("");
                    }
                  }
                  {
                    let dataCtr = data.attributes.eventTypes;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a('string');
                      expect(data).to.be("");
                    }
                  }
                  {
                    let dataCtr = data.attributes.targetAudience;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a('string');
                      expect(data).to.be("");
                    }
                  }
                  expect(data.attributes.capacity).to.be.a('number');
                  expect(data.attributes.capacity).to.be(0);
                  {
                    let dataCtr = data.attributes.eligibility;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a('string');
                      expect(data).to.be("");
                    }
                  }
                  expect(data.attributes.contact).to.be.a('string');
                  expect(data.attributes.contact).to.be("");
                  {
                    let dataCtr = data.attributes.hostInstitutions;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a('string');
                      expect(data).to.be("");
                    }
                  }
                  {
                    let dataCtr = data.attributes.scientificTopics;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a(TessJsonApi.OntologyTerm);
                      expect(data.preferredLabel).to.be.a('string');
                      expect(data.preferredLabel).to.be("");
                      expect(data.uri).to.be.a('string');
                      expect(data.uri).to.be("");
      
                            }
                  }
                  {
                    let dataCtr = data.attributes.operations;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a(TessJsonApi.OntologyTerm);
                      expect(data.preferredLabel).to.be.a('string');
                      expect(data.preferredLabel).to.be("");
                      expect(data.uri).to.be.a('string');
                      expect(data.uri).to.be("");
      
                            }
                  }
                  {
                    let dataCtr = data.attributes.externalResources;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a(TessJsonApi.ExternalResource);
                      expect(data.title).to.be.a('string');
                      expect(data.title).to.be("");
                      expect(data.url).to.be.a('string');
                      expect(data.url).to.be("");
                      expect(data.createdAt).to.be.a(Date);
                      expect(data.createdAt).to.be(new Date());
                      expect(data.updatedAt).to.be.a(Date);
                      expect(data.updatedAt).to.be(new Date());
                      expect(data.apiUrl).to.be.a('string');
                      expect(data.apiUrl).to.be("");
                      expect(data.type).to.be.a('string');
                      expect(data.type).to.be("");
      
                            }
                  }
                  expect(data.attributes.report).to.be.a(Object);
                  expect(data.attributes.report).to.be();
                expect(data.relationships).to.be.a(Object);
                expect(data.relationships).to.be();
                expect(data.links).to.be.a(Object);
                expect(data.links).to.be();

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('eventsSlugGet', function() {
        it('should call eventsSlugGet successfully', function(done) {
          // TODO: uncomment, update parameter values for eventsSlugGet call and complete the assertions
          /*
          var slug = "slug_example";

          instance.eventsSlugGet(slug, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TessJsonApi.Event);
            expect(data.errors).to.be.a(Object);
            expect(data.errors).to.be();
            expect(data.meta).to.be.a(Object);
            expect(data.meta).to.be();
            expect(data.links).to.be.a(Object);
            expect(data.links).to.be();
            expect(data.included).to.be.a(Object);
            expect(data.included).to.be();
            expect(data.jsonapi).to.be.a(Object);
            expect(data.jsonapi).to.be();
            expect(data.data).to.be.a(TessJsonApi.EventResource);
                  expect(data.data.id).to.be.a('string');
              expect(data.data.id).to.be("");
              expect(data.data.type).to.be.a('string');
              expect(data.data.type).to.be("");
              expect(data.data.meta).to.be.a(Object);
              expect(data.data.meta).to.be();
              expect(data.data.attributes).to.be.a(TessJsonApi.EventAttributes);
                    expect(data.data.attributes.slug).to.be.a('string');
                expect(data.data.attributes.slug).to.be("");
                expect(data.data.attributes.title).to.be.a('string');
                expect(data.data.attributes.title).to.be("");
                expect(data.data.attributes.subtitle).to.be.a('string');
                expect(data.data.attributes.subtitle).to.be("");
                expect(data.data.attributes.url).to.be.a('string');
                expect(data.data.attributes.url).to.be("");
                expect(data.data.attributes.organizer).to.be.a('string');
                expect(data.data.attributes.organizer).to.be("");
                expect(data.data.attributes.description).to.be.a('string');
                expect(data.data.attributes.description).to.be("");
                expect(data.data.attributes.start).to.be.a(Date);
                expect(data.data.attributes.start).to.be(new Date());
                expect(data.data.attributes.end).to.be.a(Date);
                expect(data.data.attributes.end).to.be(new Date());
                expect(data.data.attributes.sponsor).to.be.a('string');
                expect(data.data.attributes.sponsor).to.be("");
                expect(data.data.attributes.venue).to.be.a('string');
                expect(data.data.attributes.venue).to.be("");
                expect(data.data.attributes.city).to.be.a('string');
                expect(data.data.attributes.city).to.be("");
                expect(data.data.attributes.country).to.be.a('string');
                expect(data.data.attributes.country).to.be("");
                expect(data.data.attributes.county).to.be.a('string');
                expect(data.data.attributes.county).to.be("");
                expect(data.data.attributes.postcode).to.be.a('string');
                expect(data.data.attributes.postcode).to.be("");
                expect(data.data.attributes.latitude).to.be.a('string');
                expect(data.data.attributes.latitude).to.be("");
                expect(data.data.attributes.longitude).to.be.a('string');
                expect(data.data.attributes.longitude).to.be("");
                expect(data.data.attributes.createdAt).to.be.a(Date);
                expect(data.data.attributes.createdAt).to.be(new Date());
                expect(data.data.attributes.updatedAt).to.be.a(Date);
                expect(data.data.attributes.updatedAt).to.be(new Date());
                {
                  let dataCtr = data.data.attributes.keywords;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a('string');
                    expect(data).to.be("");
                  }
                }
                {
                  let dataCtr = data.data.attributes.eventTypes;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a('string');
                    expect(data).to.be("");
                  }
                }
                {
                  let dataCtr = data.data.attributes.targetAudience;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a('string');
                    expect(data).to.be("");
                  }
                }
                expect(data.data.attributes.capacity).to.be.a('number');
                expect(data.data.attributes.capacity).to.be(0);
                {
                  let dataCtr = data.data.attributes.eligibility;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a('string');
                    expect(data).to.be("");
                  }
                }
                expect(data.data.attributes.contact).to.be.a('string');
                expect(data.data.attributes.contact).to.be("");
                {
                  let dataCtr = data.data.attributes.hostInstitutions;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a('string');
                    expect(data).to.be("");
                  }
                }
                {
                  let dataCtr = data.data.attributes.scientificTopics;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(TessJsonApi.OntologyTerm);
                    expect(data.preferredLabel).to.be.a('string');
                    expect(data.preferredLabel).to.be("");
                    expect(data.uri).to.be.a('string');
                    expect(data.uri).to.be("");
    
                          }
                }
                {
                  let dataCtr = data.data.attributes.operations;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(TessJsonApi.OntologyTerm);
                    expect(data.preferredLabel).to.be.a('string');
                    expect(data.preferredLabel).to.be("");
                    expect(data.uri).to.be.a('string');
                    expect(data.uri).to.be("");
    
                          }
                }
                {
                  let dataCtr = data.data.attributes.externalResources;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(TessJsonApi.ExternalResource);
                    expect(data.title).to.be.a('string');
                    expect(data.title).to.be("");
                    expect(data.url).to.be.a('string');
                    expect(data.url).to.be("");
                    expect(data.createdAt).to.be.a(Date);
                    expect(data.createdAt).to.be(new Date());
                    expect(data.updatedAt).to.be.a(Date);
                    expect(data.updatedAt).to.be(new Date());
                    expect(data.apiUrl).to.be.a('string');
                    expect(data.apiUrl).to.be("");
                    expect(data.type).to.be.a('string');
                    expect(data.type).to.be("");
    
                          }
                }
                expect(data.data.attributes.report).to.be.a(Object);
                expect(data.data.attributes.report).to.be();
              expect(data.data.relationships).to.be.a(Object);
              expect(data.data.relationships).to.be();
              expect(data.data.links).to.be.a(Object);
              expect(data.data.links).to.be();

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
