/*
 * TeSS JSON-API
 * An implementation of the API for ELIXIR's TeSS, following JSON-API (http://jsonapi.org/) standards.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: tess-support@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TessJsonApi);
  }
}(this, function(expect, TessJsonApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TessJsonApi.UsersApi();
  });

  describe('(package)', function() {
    describe('UsersApi', function() {
      describe('usersGet', function() {
        it('should call usersGet successfully', function(done) {
          // TODO: uncomment usersGet call and complete the assertions
          /*

          instance.usersGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TessJsonApi.UserCollection);
            expect(data.errors).to.be.a(Object);
            expect(data.errors).to.be();
            expect(data.meta).to.be.a(Object);
            expect(data.meta).to.be();
            expect(data.links).to.be.a(Object);
            expect(data.links).to.be();
            expect(data.included).to.be.a(Object);
            expect(data.included).to.be();
            expect(data.jsonapi).to.be.a(Object);
            expect(data.jsonapi).to.be();
            {
              let dataCtr = data.data;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(TessJsonApi.UserResource);
                expect(data.id).to.be.a('string');
                expect(data.id).to.be("");
                expect(data.type).to.be.a('string');
                expect(data.type).to.be("");
                expect(data.meta).to.be.a(Object);
                expect(data.meta).to.be();
                expect(data.attributes).to.be.a(TessJsonApi.UserAttributes);
                      expect(data.attributes.slug).to.be.a('string');
                  expect(data.attributes.slug).to.be("");
                  expect(data.attributes.firstname).to.be.a('string');
                  expect(data.attributes.firstname).to.be("");
                  expect(data.attributes.surname).to.be.a('string');
                  expect(data.attributes.surname).to.be("");
                  expect(data.attributes.createdAt).to.be.a(Date);
                  expect(data.attributes.createdAt).to.be(new Date());
                  expect(data.attributes.updatedAt).to.be.a(Date);
                  expect(data.attributes.updatedAt).to.be(new Date());
                expect(data.relationships).to.be.a(Object);
                expect(data.relationships).to.be();
                expect(data.links).to.be.a(Object);
                expect(data.links).to.be();

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('usersSlugGet', function() {
        it('should call usersSlugGet successfully', function(done) {
          // TODO: uncomment, update parameter values for usersSlugGet call and complete the assertions
          /*
          var slug = "slug_example";

          instance.usersSlugGet(slug, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(TessJsonApi.User);
            expect(data.errors).to.be.a(Object);
            expect(data.errors).to.be();
            expect(data.meta).to.be.a(Object);
            expect(data.meta).to.be();
            expect(data.links).to.be.a(Object);
            expect(data.links).to.be();
            expect(data.included).to.be.a(Object);
            expect(data.included).to.be();
            expect(data.jsonapi).to.be.a(Object);
            expect(data.jsonapi).to.be();
            expect(data.data).to.be.a(TessJsonApi.UserResource);
                  expect(data.data.id).to.be.a('string');
              expect(data.data.id).to.be("");
              expect(data.data.type).to.be.a('string');
              expect(data.data.type).to.be("");
              expect(data.data.meta).to.be.a(Object);
              expect(data.data.meta).to.be();
              expect(data.data.attributes).to.be.a(TessJsonApi.UserAttributes);
                    expect(data.data.attributes.slug).to.be.a('string');
                expect(data.data.attributes.slug).to.be("");
                expect(data.data.attributes.firstname).to.be.a('string');
                expect(data.data.attributes.firstname).to.be("");
                expect(data.data.attributes.surname).to.be.a('string');
                expect(data.data.attributes.surname).to.be("");
                expect(data.data.attributes.createdAt).to.be.a(Date);
                expect(data.data.attributes.createdAt).to.be(new Date());
                expect(data.data.attributes.updatedAt).to.be.a(Date);
                expect(data.data.attributes.updatedAt).to.be(new Date());
              expect(data.data.relationships).to.be.a(Object);
              expect(data.data.relationships).to.be();
              expect(data.data.links).to.be.a(Object);
              expect(data.data.links).to.be();

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
